import Provider from "./components/provider";
import "./globals.css";

export const metadata = {
  title: "Next auth test",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <Provider>
        <body className="bg-gray-900">{children}</body>
      </Provider>
    </html>
  );
}
